ip = "127.0.0.1"
port = 9030
db_name = "stats_test"
user = "root"
table_size = 10000000
db_gen_path = "/home/kikyo/Documents/source/doris-dbgen/doris-dbgen"
be_path = "/home/kikyo/Documents/source/doris/output/be"
fe_path = "/home/kikyo/Documents/source/doris/output/fe"
be_bin_path = be_path + "/bin"
fe_bin_path = fe_path + "/bin"
fe_conf_file_path = fe_path + "/conf/fe.conf"
fe_boot_timeout_in_sec = 60
fe_precache_load_cost_time_in_sec = 15
internal_db = "__internal_schema"
fe_analyze_timeout_in_sec = 300
be_boot_cost_time_in_sec = 20
report_output_path = "/tmp/stats_report"
query_timeout_in_sec = 1800
auto_analyze_interval_in_minutes = 1